//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.ConstanciaElecontronica {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.ConstanciaElecontronica.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Acepto.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adulto Sin Identificación.
        /// </summary>
        internal static string adutlWithOut {
            get {
                return ResourceManager.GetString("adutlWithOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Edad:.
        /// </summary>
        internal static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hermano (a).
        /// </summary>
        internal static string Brother {
            get {
                return ResourceManager.GetString("Brother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro Civil.
        /// </summary>
        internal static string civilRegistry {
            get {
                return ResourceManager.GetString("civilRegistry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Limpiar.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cédula.
        /// </summary>
        internal static string ColombianCard {
            get {
                return ResourceManager.GetString("ColombianCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Primo.
        /// </summary>
        internal static string cousin {
            get {
                return ResourceManager.GetString("cousin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Carnet Diplomático.
        /// </summary>
        internal static string diplomatCard {
            get {
                return ResourceManager.GetString("diplomatCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Con la firma de este documento manifiesto que he sido informado por el personal de admisiones del HOSPITAL UNIVERSITARIO SAN IGNACIO (en adelante “HUSI”) que: 
        ///                            
        ///    a.	Con ocasión de mi atención en salud, el HUSI deberá recolectar mis datos personales y se compromete a darles un uso responsable y confidencial, conforme a la Política de Tratamiento de Datos Personales  del HUSI disponible en www.husi.org.co
        ///
        ///    b.	Que en el curso de mi atención tendré que dar información pers [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string document {
            get {
                return ResourceManager.GetString("document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Padre.
        /// </summary>
        internal static string Father {
            get {
                return ResourceManager.GetString("Father", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento Extranjero.
        /// </summary>
        internal static string foreignCertificate {
            get {
                return ResourceManager.GetString("foreignCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cédula de Extranjería.
        /// </summary>
        internal static string ForeignerCard {
            get {
                return ResourceManager.GetString("ForeignerCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Amigo (a).
        /// </summary>
        internal static string Friend {
            get {
                return ResourceManager.GetString("Friend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sexo:.
        /// </summary>
        internal static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tarjeta de Identidad.
        /// </summary>
        internal static string IdentityCard {
            get {
                return ResourceManager.GetString("IdentityCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Información del paciente.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nacido Vivo.
        /// </summary>
        internal static string liveBirth {
            get {
                return ResourceManager.GetString("liveBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esposo (a).
        /// </summary>
        internal static string Married {
            get {
                return ResourceManager.GetString("Married", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Menor sin identificación.
        /// </summary>
        internal static string minorWithOut {
            get {
                return ResourceManager.GetString("minorWithOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Madre.
        /// </summary>
        internal static string Mother {
            get {
                return ResourceManager.GetString("Mother", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre:.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número documento:.
        /// </summary>
        internal static string NumDoc {
            get {
                return ResourceManager.GetString("NumDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pasaporte de la ONU.
        /// </summary>
        internal static string ONUpassport {
            get {
                return ResourceManager.GetString("ONUpassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Otro.
        /// </summary>
        internal static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pasaporte.
        /// </summary>
        internal static string passport {
            get {
                return ResourceManager.GetString("passport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Paciente:.
        /// </summary>
        internal static string Patient {
            get {
                return ResourceManager.GetString("Patient", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre completo.
        /// </summary>
        internal static string PName {
            get {
                return ResourceManager.GetString("PName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Número de identificación.
        /// </summary>
        internal static string PNumDoc {
            get {
                return ResourceManager.GetString("PNumDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejm: Hijo 1.
        /// </summary>
        internal static string pSon {
            get {
                return ResourceManager.GetString("pSon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Relación:.
        /// </summary>
        internal static string Relation {
            get {
                return ResourceManager.GetString("Relation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Salvo Conducto en Permanencia.
        /// </summary>
        internal static string SafeConduct {
            get {
                return ResourceManager.GetString("SafeConduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a seleccione una opción.
        /// </summary>
        internal static string SelectedOption {
            get {
                return ResourceManager.GetString("SelectedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Firma sobre la línea.
        /// </summary>
        internal static string Sing {
            get {
                return ResourceManager.GetString("Sing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hijo (a).
        /// </summary>
        internal static string Son {
            get {
                return ResourceManager.GetString("Son", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Permiso Especial Permanencia.
        /// </summary>
        internal static string specialPermission {
            get {
                return ResourceManager.GetString("specialPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorización de Tratamiento de Datos.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos Acompañante.
        /// </summary>
        internal static string titleAccompanying {
            get {
                return ResourceManager.GetString("titleAccompanying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo documento:.
        /// </summary>
        internal static string TypeDoc {
            get {
                return ResourceManager.GetString("TypeDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Cuál?:.
        /// </summary>
        internal static string which {
            get {
                return ResourceManager.GetString("which", resourceCulture);
            }
        }
    }
}
